#!/bin/bash
sudo apt update
sudo apt upgrade -y
sudo apt dist-upgrade -y
sudo apt install p7zip-full -y
sudo apt install fail2ban -y
sudo apt install git -y
sudo apt install cmake -y
sudo apt install libpcap-dev -y
sudo apt install autoconf -y
sudo apt install python-pip -y
sudo apt install python-pil -y
sudo apt install python-numpy -y
sudo pip install RPi.GPIO
sudo pip install spidev
sudo pip install pexpect
sudo pip install manifest-tool
sudo pip2 install python-can 
sudo apt install python3-pip -y
sudo apt install python3-pil -y
sudo apt install python3-numpy -y
sudo pip3 install RPi.GPIO
sudo pip3 install spidev 
sudo pip3 install python-can
sudo pip3 install can-isotp	
sudo pip3 install treelib
sudo pip3 install pexpect
sudo pip3 install manifest-tool
sudo apt install build-essential -y
sudo apt install raspberrypi-kernel-headers -y
sudo apt install linux-kernel-headers -y
sudo apt install libusb-1.0-0-dev -y
sudo apt install libboost-all-dev -y
sudo apt install doxygen -y
sudo apt install python-pydot -y
sudo apt install python-pydot-ng -y
sudo apt install graphviz -y
sudo apt install libconfuse-dev -y
sudo apt install libffi-dev -y
sudo apt install libbsd-dev -y
sudo apt install xorg-dev -y
sudo apt install autopoint -y
sudo apt install flex -y
sudo apt install gawk -y
sudo apt install lexicon -y
sudo apt install gettext -y
sudo apt install binutils -y
sudo apt install tmate -y
sudo apt install samba -y
sudo apt install lynx -y
sudo apt install binwalk -y
sudo apt install screen -y
sudo apt install can-utils -y
# I tried to put it all on one or two lines and it was just horrible.
# I was trying to satisfy all the requirments that alow you to do extra little things when having things install. We can scale this back.  


# git clone https://github.com/martinh/libconfuse.git
# this next line needs to be autoreconf untill I fix it just build it normally
# sudo ./autogen.sh ~/libconfuse/canfigure.ac
# sudo ~/libconfuse/configure
# sudo make -C ~/libconfuse/. -j4
# sudo make -C ~/libconfuse/. install

# getting ride of this for 
#git clone https://github.com/linux-can/can-utils.git
#sudo autoreconf --force --install -Wall ~/can-utils/configure.ac
#sudo ~/can-utils/configure
#sudo make -C ~/can-utils/. -j8
# # Might want to try this out cmake -DCMAKE_TOOLCHAIN_FILE=~/rpi/tools/build/cmake/rpi.toolchain.cmake .. && make
#sudo make -C ~/can-utils/. install

# might no longer need this I think I do:
git clone https://github.com/hartkopp/can-isotp.git
sudo make -C ~/can-isotp/ -j4
sudo make modules_install -C ~/can-isotp/
sudo modprobe can
sudo insmod ~/can-isotp/net/can/can-isotp.ko

git clone https://github.com/intrepidcs/intrepid-socketcan-kernel-module.git
#just cd in and make it I cant get it to work in the script
#sudo make -C /lib/modules/$(uname -r)/build M=~/intrepid-socketcan-kernel-module/ modules -j4
#sudo make -C ~/intrepid-socketcan-kernel-module/. install
#cd intrepid-socketcan-kernel-module
# sudo insmod ~/intrepid-socketcan-kernel-module/intrepid.ko

git clone --recursive https://github.com/intrepidcs/icsscand.git
sudo mkdir -p ~/icsscand/build
sudo cmake -S ~/icsscand/ -B ~/icsscand/build -DCMAKE_BUILD_TYPE=Release
sudo make -C ~/icsscand/build/. -j8
sudo ~/icsscand/build/libicsneo-socketcan-daemon

sudo echo "can" >> /etc/modules
sudo echo "can_raw" >> /etc/modules
sudo echo "can_dev" >> /etc/modules
